### ISSUE TITLE
Milestone 4 - Vignettes & Documentation

### ISSUE THREAD

**Issue by LukeAC** [UBC-MDS/canadacovidmetricsR#25]

**Comment by LukeAC** [comment]
- Review ROxygen2 docstrings and update where required @LukeAC 
- Code-cleanup(?) @LukeAC 
-- verify `check()` functionality in R @adammorphy 
- [Vignettes ](https://r-pkgs.org/vignettes.html#vignettes) @valli180 
- [pkgdown](https://pkgdown.r-lib.org/) @LukeAC

**Comment by LukeAC** [comment]
@valli180 Hey Valli just checking in - how goes the work on the Vignettes component of this?

**Comment by valli180** [comment]
Yes, Done with my assignments. working on the group project now
